const state = { coins: [], sort: 'market_cap', direction: 'desc', mode: 'all', favorites: new Set(JSON.parse(localStorage.getItem('coinscope-favorites') || '[]')), showingFavorites: false };
const $ = (id) => document.getElementById(id);
const money = (value, compact = false) => new Intl.NumberFormat('ru-RU', { style: 'currency', currency: 'USD', notation: compact ? 'compact' : 'standard', maximumFractionDigits: value < 1 ? 5 : 2 }).format(value || 0);
const percent = (value) => `${value >= 0 ? '+' : ''}${(value || 0).toFixed(2)}%`;

function filteredCoins() {
  const query = $('searchInput').value.trim().toLowerCase();
  const change = Number($('changeRange').value), cap = Number($('marketCapFilter').value), volume = Number($('volumeFilter').value);
  return state.coins.filter((coin) => (!query || `${coin.name} ${coin.symbol}`.toLowerCase().includes(query)) && (coin.price_change_percentage_24h || 0) >= change && coin.market_cap >= cap && coin.total_volume >= volume && (!state.showingFavorites || state.favorites.has(coin.id)) && (state.mode !== 'gainers' || (coin.price_change_percentage_24h || 0) > 0) && (state.mode !== 'volume' || coin.total_volume >= 100000000)).sort((a, b) => (a[state.sort] - b[state.sort]) * (state.direction === 'asc' ? 1 : -1));
}
function render() {
  const coins = filteredCoins(), tbody = $('coinRows'), template = $('coinRowTemplate');
  $('resultsTitle').textContent = state.showingFavorites ? 'Избранные монеты' : state.mode === 'gainers' ? 'Лидеры роста' : state.mode === 'volume' ? 'Высокий объём' : 'Все монеты';
  if (!coins.length) { tbody.innerHTML = '<tr><td class="loading" colspan="7">По выбранным условиям ничего не найдено.</td></tr>'; return; }
  tbody.replaceChildren(...coins.map((coin) => { const row = template.content.firstElementChild.cloneNode(true), isSaved = state.favorites.has(coin.id), change = coin.price_change_percentage_24h || 0; row.querySelector('.rank').textContent = coin.market_cap_rank || '—'; const image = row.querySelector('img'); image.src = coin.image; image.alt = ''; row.querySelector('.asset strong').textContent = coin.name; row.querySelector('.asset small').textContent = coin.symbol; row.querySelector('.price').textContent = money(coin.current_price); const changeCell = row.querySelector('.change'); changeCell.textContent = percent(change); changeCell.classList.add(change >= 0 ? 'positive' : 'negative'); row.querySelector('.volume').textContent = money(coin.total_volume, true); row.querySelector('.cap').textContent = money(coin.market_cap, true); const star = row.querySelector('.star'); star.textContent = isSaved ? '★' : '☆'; star.classList.toggle('saved', isSaved); star.setAttribute('aria-label', isSaved ? 'Убрать из избранного' : 'Добавить в избранное'); star.addEventListener('click', () => { isSaved ? state.favorites.delete(coin.id) : state.favorites.add(coin.id); localStorage.setItem('coinscope-favorites', JSON.stringify([...state.favorites])); render(); }); return row; }));
}
function updateSummary(data) { $('marketCap').textContent = money(data.reduce((sum, coin) => sum + (coin.market_cap || 0), 0), true); $('marketVolume').textContent = money(data.reduce((sum, coin) => sum + (coin.total_volume || 0), 0), true); $('coinCount').textContent = data.length; }
async function loadCoins() { const button = $('refreshButton'); button.disabled = true; $('marketStatus').textContent = 'Обновляем данные'; try { const response = await fetch('https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=100&page=1&sparkline=false&price_change_percentage=24h', { headers: { accept: 'application/json' } }); if (!response.ok) throw new Error('Market API unavailable'); state.coins = await response.json(); updateSummary(state.coins); $('updatedAt').textContent = `Обновлено: ${new Intl.DateTimeFormat('ru-RU', { hour: '2-digit', minute: '2-digit' }).format(new Date())}`; $('marketStatus').textContent = 'Данные актуальны'; render(); } catch (error) { $('marketStatus').textContent = 'Нет связи с API'; $('coinRows').innerHTML = '<tr><td class="loading" colspan="7">Не удалось загрузить рынок. Попробуйте обновить страницу.</td></tr>'; } finally { button.disabled = false; } }
document.querySelectorAll('input, select').forEach((element) => element.addEventListener('input', render)); $('changeRange').addEventListener('input', (event) => { $('changeValue').textContent = `${Number(event.target.value) > 0 ? '+' : ''}${event.target.value}%`; }); document.querySelectorAll('[data-filter]').forEach((button) => button.addEventListener('click', () => { state.mode = button.dataset.filter; document.querySelectorAll('[data-filter]').forEach((item) => item.classList.toggle('active', item === button)); render(); })); document.querySelectorAll('[data-sort]').forEach((button) => button.addEventListener('click', () => { const field = button.dataset.sort; state.direction = state.sort === field && state.direction === 'desc' ? 'asc' : 'desc'; state.sort = field; render(); })); $('watchlistButton').addEventListener('click', () => { state.showingFavorites = !state.showingFavorites; $('watchlistButton').textContent = state.showingFavorites ? '★ Показать все монеты' : '☆ Показать избранное'; render(); }); $('resetFilters').addEventListener('click', () => { $('searchInput').value = ''; $('changeRange').value = -10; $('changeValue').textContent = '−10%'; $('marketCapFilter').value = '0'; $('volumeFilter').value = '0'; state.mode = 'all'; state.showingFavorites = false; $('watchlistButton').textContent = '☆ Показать избранное'; document.querySelectorAll('[data-filter]').forEach((item) => item.classList.toggle('active', item.dataset.filter === 'all')); render(); }); $('refreshButton').addEventListener('click', loadCoins); loadCoins();
